spring:
  application:
    name: demo-gateway-service
  #cloud:
    #loadbalancer:
      #ribbon:
        #enabled: true
server:
  port: 8091

eureka:
  client:
    #registerWithEureka: true
    #fetchRegistry: true
    sevice-Url:
      defaultZone: http://localhost:8761/eureka/
  #instance:
    #hostname: localhost